---
language: go

go:
  - 1.8
  - 1.9

branches:
  only:
    - master

before_script:
  - go get github.com/golang/dep/cmd/dep
  - dep ensure

script: 
  - go test -v -race $(go list ./... | grep -v /vendor/)  # Run all the tests with the race detector enabled
