// Code generated by protoc-gen-go.
// source: gokuserver.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	gokuserver.proto

It has these top-level messages:
	Error
	Element
	InsertRequest
	InsertReply
	DeleteRequest
	DeleteReply
	SelectRequest
	SelectReply
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Error struct {
	Code    int64  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Error) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Element struct {
	Member      string `protobuf:"bytes,3,opt,name=member" json:"member,omitempty"`
	TimestampNs int64  `protobuf:"varint,4,opt,name=timestamp_ns,json=timestampNs" json:"timestamp_ns,omitempty"`
	TtlNs       int64  `protobuf:"varint,5,opt,name=ttl_ns,json=ttlNs" json:"ttl_ns,omitempty"`
}

func (m *Element) Reset()                    { *m = Element{} }
func (m *Element) String() string            { return proto.CompactTextString(m) }
func (*Element) ProtoMessage()               {}
func (*Element) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Element) GetMember() string {
	if m != nil {
		return m.Member
	}
	return ""
}

func (m *Element) GetTimestampNs() int64 {
	if m != nil {
		return m.TimestampNs
	}
	return 0
}

func (m *Element) GetTtlNs() int64 {
	if m != nil {
		return m.TtlNs
	}
	return 0
}

type InsertRequest struct {
	SlotId      int64  `protobuf:"varint,1,opt,name=slot_id,json=slotId" json:"slot_id,omitempty"`
	Key         string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	Member      string `protobuf:"bytes,3,opt,name=member" json:"member,omitempty"`
	TimestampNs int64  `protobuf:"varint,4,opt,name=timestamp_ns,json=timestampNs" json:"timestamp_ns,omitempty"`
	TtlNs       int64  `protobuf:"varint,5,opt,name=ttl_ns,json=ttlNs" json:"ttl_ns,omitempty"`
}

func (m *InsertRequest) Reset()                    { *m = InsertRequest{} }
func (m *InsertRequest) String() string            { return proto.CompactTextString(m) }
func (*InsertRequest) ProtoMessage()               {}
func (*InsertRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *InsertRequest) GetSlotId() int64 {
	if m != nil {
		return m.SlotId
	}
	return 0
}

func (m *InsertRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *InsertRequest) GetMember() string {
	if m != nil {
		return m.Member
	}
	return ""
}

func (m *InsertRequest) GetTimestampNs() int64 {
	if m != nil {
		return m.TimestampNs
	}
	return 0
}

func (m *InsertRequest) GetTtlNs() int64 {
	if m != nil {
		return m.TtlNs
	}
	return 0
}

type InsertReply struct {
	Updated bool   `protobuf:"varint,1,opt,name=updated" json:"updated,omitempty"`
	Error   *Error `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *InsertReply) Reset()                    { *m = InsertReply{} }
func (m *InsertReply) String() string            { return proto.CompactTextString(m) }
func (*InsertReply) ProtoMessage()               {}
func (*InsertReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *InsertReply) GetUpdated() bool {
	if m != nil {
		return m.Updated
	}
	return false
}

func (m *InsertReply) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type DeleteRequest struct {
	SlotId      int64  `protobuf:"varint,1,opt,name=slot_id,json=slotId" json:"slot_id,omitempty"`
	Key         string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	Member      string `protobuf:"bytes,3,opt,name=member" json:"member,omitempty"`
	TimestampNs int64  `protobuf:"varint,4,opt,name=timestamp_ns,json=timestampNs" json:"timestamp_ns,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *DeleteRequest) GetSlotId() int64 {
	if m != nil {
		return m.SlotId
	}
	return 0
}

func (m *DeleteRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DeleteRequest) GetMember() string {
	if m != nil {
		return m.Member
	}
	return ""
}

func (m *DeleteRequest) GetTimestampNs() int64 {
	if m != nil {
		return m.TimestampNs
	}
	return 0
}

type DeleteReply struct {
	Deleted bool   `protobuf:"varint,1,opt,name=deleted" json:"deleted,omitempty"`
	Error   *Error `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *DeleteReply) Reset()                    { *m = DeleteReply{} }
func (m *DeleteReply) String() string            { return proto.CompactTextString(m) }
func (*DeleteReply) ProtoMessage()               {}
func (*DeleteReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *DeleteReply) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

func (m *DeleteReply) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type SelectRequest struct {
	SlotId      int64  `protobuf:"varint,1,opt,name=slot_id,json=slotId" json:"slot_id,omitempty"`
	Key         string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	TimestampNs int64  `protobuf:"varint,3,opt,name=timestamp_ns,json=timestampNs" json:"timestamp_ns,omitempty"`
}

func (m *SelectRequest) Reset()                    { *m = SelectRequest{} }
func (m *SelectRequest) String() string            { return proto.CompactTextString(m) }
func (*SelectRequest) ProtoMessage()               {}
func (*SelectRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *SelectRequest) GetSlotId() int64 {
	if m != nil {
		return m.SlotId
	}
	return 0
}

func (m *SelectRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SelectRequest) GetTimestampNs() int64 {
	if m != nil {
		return m.TimestampNs
	}
	return 0
}

type SelectReply struct {
	Elements []*Element `protobuf:"bytes,1,rep,name=elements" json:"elements,omitempty"`
	Error    *Error     `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *SelectReply) Reset()                    { *m = SelectReply{} }
func (m *SelectReply) String() string            { return proto.CompactTextString(m) }
func (*SelectReply) ProtoMessage()               {}
func (*SelectReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *SelectReply) GetElements() []*Element {
	if m != nil {
		return m.Elements
	}
	return nil
}

func (m *SelectReply) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*Error)(nil), "pb.Error")
	proto.RegisterType((*Element)(nil), "pb.Element")
	proto.RegisterType((*InsertRequest)(nil), "pb.InsertRequest")
	proto.RegisterType((*InsertReply)(nil), "pb.InsertReply")
	proto.RegisterType((*DeleteRequest)(nil), "pb.DeleteRequest")
	proto.RegisterType((*DeleteReply)(nil), "pb.DeleteReply")
	proto.RegisterType((*SelectRequest)(nil), "pb.SelectRequest")
	proto.RegisterType((*SelectReply)(nil), "pb.SelectReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for GokuServer service

type GokuServerClient interface {
	Insert(ctx context.Context, in *InsertRequest, opts ...grpc.CallOption) (*InsertReply, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteReply, error)
	Select(ctx context.Context, in *SelectRequest, opts ...grpc.CallOption) (*SelectReply, error)
}

type gokuServerClient struct {
	cc *grpc.ClientConn
}

func NewGokuServerClient(cc *grpc.ClientConn) GokuServerClient {
	return &gokuServerClient{cc}
}

func (c *gokuServerClient) Insert(ctx context.Context, in *InsertRequest, opts ...grpc.CallOption) (*InsertReply, error) {
	out := new(InsertReply)
	err := grpc.Invoke(ctx, "/pb.GokuServer/Insert", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gokuServerClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteReply, error) {
	out := new(DeleteReply)
	err := grpc.Invoke(ctx, "/pb.GokuServer/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gokuServerClient) Select(ctx context.Context, in *SelectRequest, opts ...grpc.CallOption) (*SelectReply, error) {
	out := new(SelectReply)
	err := grpc.Invoke(ctx, "/pb.GokuServer/Select", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GokuServer service

type GokuServerServer interface {
	Insert(context.Context, *InsertRequest) (*InsertReply, error)
	Delete(context.Context, *DeleteRequest) (*DeleteReply, error)
	Select(context.Context, *SelectRequest) (*SelectReply, error)
}

func RegisterGokuServerServer(s *grpc.Server, srv GokuServerServer) {
	s.RegisterService(&_GokuServer_serviceDesc, srv)
}

func _GokuServer_Insert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GokuServerServer).Insert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GokuServer/Insert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GokuServerServer).Insert(ctx, req.(*InsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GokuServer_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GokuServerServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GokuServer/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GokuServerServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GokuServer_Select_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GokuServerServer).Select(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GokuServer/Select",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GokuServerServer).Select(ctx, req.(*SelectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GokuServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.GokuServer",
	HandlerType: (*GokuServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Insert",
			Handler:    _GokuServer_Insert_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _GokuServer_Delete_Handler,
		},
		{
			MethodName: "Select",
			Handler:    _GokuServer_Select_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gokuserver.proto",
}

func init() { proto.RegisterFile("gokuserver.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 381 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x93, 0xc1, 0x4e, 0xc2, 0x30,
	0x1c, 0xc6, 0x19, 0x63, 0x03, 0xfe, 0x93, 0x88, 0x4d, 0xd4, 0xc5, 0x8b, 0xb8, 0x8b, 0x9c, 0x76,
	0xc0, 0xf8, 0x02, 0x46, 0xa2, 0x5c, 0x38, 0x8c, 0x83, 0x89, 0xc6, 0x10, 0xc6, 0xfe, 0x21, 0x84,
	0x8e, 0xd6, 0xb6, 0x33, 0xe1, 0x1d, 0x7c, 0x04, 0x1f, 0xd6, 0xb4, 0xdd, 0x08, 0xe8, 0x81, 0xc4,
	0x44, 0x6f, 0xfd, 0xfe, 0xfd, 0xd2, 0xfd, 0xbe, 0xaf, 0x1d, 0x74, 0x17, 0x6c, 0x55, 0x48, 0x14,
	0xef, 0x28, 0x62, 0x2e, 0x98, 0x62, 0xa4, 0xce, 0xd3, 0xe8, 0x16, 0xbc, 0xa1, 0x10, 0x4c, 0x10,
	0x02, 0x8d, 0x39, 0xcb, 0x30, 0x74, 0x7a, 0x4e, 0xdf, 0x4d, 0xcc, 0x9a, 0x84, 0xd0, 0xcc, 0x51,
	0xca, 0xd9, 0x02, 0xc3, 0x7a, 0xcf, 0xe9, 0xb7, 0x93, 0x4a, 0x46, 0x2f, 0xd0, 0x1c, 0x52, 0xcc,
	0x71, 0xad, 0xc8, 0x19, 0xf8, 0x39, 0xe6, 0x29, 0x8a, 0xd0, 0x35, 0x9e, 0x52, 0x91, 0x2b, 0x38,
	0x52, 0xcb, 0x1c, 0xa5, 0x9a, 0xe5, 0x7c, 0xba, 0x96, 0x61, 0xc3, 0x1c, 0x1c, 0x6c, 0x67, 0x63,
	0x49, 0x4e, 0xc1, 0x57, 0x8a, 0xea, 0x4d, 0xcf, 0x6c, 0x7a, 0x4a, 0xd1, 0xb1, 0x8c, 0x3e, 0x1c,
	0xe8, 0x8c, 0xd6, 0x12, 0x85, 0x4a, 0xf0, 0xad, 0x40, 0xa9, 0xc8, 0x39, 0x34, 0x25, 0x65, 0x6a,
	0xba, 0xcc, 0x4a, 0x3e, 0x5f, 0xcb, 0x51, 0x46, 0xba, 0xe0, 0xae, 0x70, 0x53, 0xd2, 0xe9, 0xe5,
	0x1f, 0xe0, 0x3c, 0x42, 0x50, 0xd1, 0x70, 0xba, 0xd1, 0xa5, 0x14, 0x3c, 0x9b, 0x29, 0xb4, 0x2c,
	0xad, 0xa4, 0x92, 0xe4, 0x12, 0x3c, 0xd4, 0x5d, 0x1a, 0x9c, 0x60, 0xd0, 0x8e, 0x79, 0x1a, 0x9b,
	0x72, 0x13, 0x3b, 0x8f, 0x0a, 0xe8, 0xdc, 0x23, 0x45, 0x85, 0xff, 0x9a, 0x4b, 0x07, 0xa8, 0x3e,
	0x5b, 0x06, 0xc8, 0x8c, 0xdc, 0x06, 0x28, 0xe5, 0xe1, 0x00, 0xaf, 0xd0, 0x99, 0x20, 0xc5, 0xf9,
	0x6f, 0x2e, 0xe6, 0x3b, 0xa8, 0xfb, 0x13, 0xf4, 0x09, 0x82, 0xea, 0x78, 0x0d, 0x7a, 0x0d, 0x2d,
	0xb4, 0x8f, 0x4c, 0x86, 0x4e, 0xcf, 0xed, 0x07, 0x83, 0xc0, 0x10, 0xd9, 0x59, 0xb2, 0xdd, 0x3c,
	0xc8, 0x3d, 0xf8, 0x74, 0x00, 0x1e, 0xd8, 0xaa, 0x98, 0x98, 0xe7, 0x4f, 0x62, 0xf0, 0xed, 0x8d,
	0x92, 0x13, 0x6d, 0xdd, 0x7b, 0x6b, 0x17, 0xc7, 0xbb, 0x23, 0x4e, 0x37, 0x51, 0x4d, 0xfb, 0x6d,
	0x81, 0xd6, 0xbf, 0x77, 0x87, 0xd6, 0xbf, 0xd3, 0xaf, 0xf5, 0xdb, 0x1c, 0xd6, 0xbf, 0x57, 0x99,
	0xf5, 0xef, 0xc4, 0x8c, 0x6a, 0x77, 0x8d, 0xe7, 0x3a, 0x4f, 0x53, 0xdf, 0xfc, 0x95, 0x37, 0x5f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x37, 0xb0, 0xf2, 0x3f, 0xa9, 0x03, 0x00, 0x00,
}
